name: 🐛 バグ報告
description: サイトの誤作動があった場合はこちらにご報告ください。
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ご報告ありがとうございます！実際に問題を報告する前に、以下をお試しください：

        - **動作しているMoodle Plusのバージョンは最新**ですか？
        - **ページを再読み込み**してみましたか？
        - **ブラウザのキャッシュ・Cookieを削除**してみましたか？
        - **時間を開けて再度アクセス**してみましたか？
        - **ログアウトして再度ログイン**してみましたか？

        また、以下のことにもご注意ください。

        - **このフォームはバグ報告専用です。** 機能リクエストは[こちら](https://github.com/tomo0611/moodle-plus/issues/new?assignees=&labels=feature&projects=&template=03_feature-request.yml)からお願いします。

        以上のことを試してもまだ問題が解決しない場合は、以下に症状をできるだけ詳しく記入してください。**貴重なお時間を使ってご報告いただきありがとうございます！**

  - type: textarea
    attributes:
      label: 💡 概要
      description: どのような問題が起こっているかを簡潔にお書きください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🥰 期待されるふるまい
      description: 本当はどういうことがしたかったのかをお書きください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🤬 実際のふるまい
      description: |
        実際には何が起きたのかをお書きください。
        可能であれば、スクリーンショットやエラーログなども添付いただけますと幸いです。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 再現方法
      description: その問題が起こるまでにどのような操作をしたかを、手順別に詳細にお書きください。
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - id: environment
    type: textarea
    attributes:
      label: 💻 動作環境
      description: |
        この問題が起きた環境をお教えください。

        例:
          * URL of the Moodle site: https://moodle.example.ac.jp/
          * Model and OS of the device(s): MacBook Pro (14inch, 2021), macOS Ventura 13.4
          * Browser: Chrome 113.0.5672.126
      value: |
        * URL of the Moodle site:
        * Model and OS of the device(s):
        * Browser:
      render: markdown
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 以下に当てはまる場合はチェックしてください。
      description: |
        Check the items that apply. All items are optional. Check only if applicable.

        項目はすべて任意です。当てはまる場合のみチェックしてください。
      options:
        - label: はい、私はこのバグに自分で対処して、このリポジトリにPull Requestを送信する予定です。
